import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import NavBar from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NavBar />
				{/* <nav>
					<Link href='/quiz'>Quiz</Link>
					<Link href='/login'>Login</Link>
				</nav> */}
				{children}
			</body>
		</html>
	);
}
